name: Hello AI-300

on:
  push:
    paths:
      - app.py
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    env:
      COURSE: AI-300

    steps:
      - uses: actions/checkout@v4

      - name: Show Repository Files
        run: ls -la

      - name: Show Variable
        run: echo "Learning $COURSE"

      - name: Show Secret
        run: echo "Hello ${{ secrets.STUDENT_NAME }}"
        
      - name: Show Current Folder
        run: pwd

      - name: Show Current User
        run: whoami

      - name: Show Operating System
        run: uname -a

      - name: Install Package
        run: pip install requests 

      - name: Run Python Script
        run: python app.py

      - name: Print Message
        run: echo "Hello AI-300"

