name: Hello AI-300

on:
  push:

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    env:
      COURSE: AI-300

    steps:
      - uses: actions/checkout@v4

      - name: Show Repository Files
        run: ls -la

      - name: Show Variable
        run: echo "Learning $COURSE"

      - name: Print Message
        run: echo "Hello AI-300"
